---
# installation tasks for docker-ce

- name: Docker-CE | Download the repo file
  get_url:
    url: "{{ docker_repo_config.baseurl }}"
    dest: /etc/yum.repos.d/docker-ce.repo
  tags:
    - install
    - docker
    - repo

- name: Docker-CE | Add repository
  ini_file:
    dest: /etc/yum.repos.d/docker-ce.repo
    section: "{{ docker_repo_config.section }}"
    option: "{{ docker_repo_config.enabled }}"
  tags:
    - install
    - docker
    - repo

- name: Docker-CE | Add users to Docker Group
  user:
    name: "{{ item }}"
    groups: docker
  with_items: "{{ docker_enabled_users | default(ansible_user_id) }}"
  tags:
    - install
    - docker
    - add_users

- name: Docker-CE | Install Docker Community Edition
  package:
    name: docker-ce
    state: present
  tags:
    - install
    - docker

- name: Docker-CE | Enable docker service and start
  systemd:
    name: docker
    state: started
    enabled: yes
  tags:
    - start
    - docker
